import 'level.dart';

class LevelData {
  static const List<Level> levels = [
    // --- DRAGON LEVELS (Fire/Sky Theme) ---
    Level(
      id: 1,
      name: 'Ashfall Ruins',
      subtitle: 'Flashback: Intro to flight & updrafts.',
      theme: 'Fire/Sky',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Dragon',
    ),
    Level(
      id: 2,
      name: 'Skybreak Canyon',
      subtitle: 'Vertical canyon leaps via thermals.',
      theme: 'Fire/Sky',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Dragon',
    ),
    Level(
      id: 3,
      name: 'The Hollow Forge',
      subtitle: 'Melt steel barriers with plasma.',
      theme: 'Fire/Sky',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Dragon',
    ),
    Level(
      id: 4,
      name: 'Storm Reckoning',
      subtitle: 'Storm combat. Conquering guilt.',
      theme: 'Fire/Sky',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Dragon',
    ),
    Level(
      id: 5,
      name: "Dragon's Trial",
      subtitle: 'Boss: Fire-elemental showdown.',
      theme: 'Fire/Sky',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Dragon',
    ),

    // --- T-REX LEVELS (Earth/Underground Theme) ---
    Level(
      id: 6,
      name: 'Cave-In Memory',
      subtitle: 'Flashback: Intro to wall-breaking slams.',
      theme: 'Earth/Underground',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'T-Rex',
    ),
    Level(
      id: 7,
      name: 'Quarry Depths',
      subtitle: 'Heavy jumping & fracturing stone.',
      theme: 'Earth/Underground',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'T-Rex',
    ),
    Level(
      id: 8,
      name: 'Foundation Breach',
      subtitle: 'Stabilize falling structures with slams.',
      theme: 'Earth/Underground',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'T-Rex',
    ),
    Level(
      id: 9,
      name: 'The Buried City',
      subtitle: 'Subterranean shockwave puzzles.',
      theme: 'Earth/Underground',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'T-Rex',
    ),
    Level(
      id: 10,
      name: "T-Rex's Trial",
      subtitle: 'Boss: Earth-elemental final stand.',
      theme: 'Earth/Underground',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'T-Rex',
    ),

    // --- CURATOR LEVELS (Ancient/Museum Theme) ---
    Level(
      id: 11,
      name: 'The Heist Echo',
      subtitle: 'Flashback: Intro to time ribbons.',
      theme: 'Ancient/Museum',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Curator',
    ),
    Level(
      id: 12,
      name: 'Sands of Memory',
      subtitle: 'Desert aging & decay mechanics.',
      theme: 'Ancient/Museum',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Curator',
    ),
    Level(
      id: 13,
      name: 'The Archive',
      subtitle: 'Restore ruined nanotech bridges.',
      theme: 'Ancient/Museum',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Curator',
    ),
    Level(
      id: 14,
      name: 'Fading Self',
      subtitle: 'Glitch landscape memory puzzles.',
      theme: 'Ancient/Museum',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Curator',
    ),
    Level(
      id: 15,
      name: "Curator's Trial",
      subtitle: 'Boss: Master of temporal echoes.',
      theme: 'Ancient/Museum',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Curator',
    ),

    // --- SHARK LEVELS (Ocean/Water Theme) ---
    Level(
      id: 16,
      name: 'The Sinking',
      subtitle: 'Flashback: Navigate submarine abyss.',
      theme: 'Ocean/Water',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Shark',
    ),
    Level(
      id: 17,
      name: 'Tide Break',
      subtitle: 'Fast-paced aquatic currents.',
      theme: 'Ocean/Water',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Shark',
    ),
    Level(
      id: 18,
      name: 'Abyss Trench',
      subtitle: 'Deep stealth. Conquer thalassophobia.',
      theme: 'Ocean/Water',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Shark',
    ),
    Level(
      id: 19,
      name: 'Flooded Harbor',
      subtitle: 'Submerged village combat arena.',
      theme: 'Ocean/Water',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Shark',
    ),
    Level(
      id: 20,
      name: "Shark's Trial",
      subtitle: 'Boss: Water-elemental storm storm.',
      theme: 'Ocean/Water',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Shark',
    ),

    // --- KITSUNE LEVELS (Urban/Tech Theme) ---
    Level(
      id: 21,
      name: 'Ghost of the Street',
      subtitle: 'Flashback: Stealth with holo-decoys.',
      theme: 'Urban/Tech',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Kitsune',
    ),
    Level(
      id: 22,
      name: 'Signal Maze',
      subtitle: 'Hacking puzzles & illusion decoys.',
      theme: 'Urban/Tech',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Kitsune',
    ),
    Level(
      id: 23,
      name: 'The Masquerade',
      subtitle: 'Neon rooftop clone battles.',
      theme: 'Urban/Tech',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Kitsune',
    ),
    Level(
      id: 24,
      name: 'Static Heart',
      subtitle: 'Drop the illusions. Trust platforming.',
      theme: 'Urban/Tech',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Kitsune',
    ),
    Level(
      id: 25,
      name: "Kitsune's Trial",
      subtitle: 'Boss: Outsmart the Hollow Mimic.',
      theme: 'Urban/Tech',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Kitsune',
    ),

    // --- TEAM LEVELS (Finale Arc) ---
    Level(
      id: 26,
      name: 'Assembly',
      subtitle: 'Full squad. Switch mid-combat.',
      theme: 'Team',
      backgroundAsset: 'backgrounds/urban_tech.png',
      heroRequirement: 'Team',
    ),
    Level(
      id: 27,
      name: 'The Rift Advance',
      subtitle: 'Dynamic switching across terrain hazards.',
      theme: 'Team',
      backgroundAsset: 'backgrounds/ancient_museum.png',
      heroRequirement: 'Team',
    ),
    Level(
      id: 28,
      name: 'Fractured Ground',
      subtitle: 'Counter elemental enemy waves.',
      theme: 'Team',
      backgroundAsset: 'backgrounds/fire_sky.png',
      heroRequirement: 'Team',
    ),
    Level(
      id: 29,
      name: "The Hollow's Heart",
      subtitle: 'Personal fear echoes in the deep rift.',
      theme: 'Team',
      backgroundAsset: 'backgrounds/earth_underground.png',
      heroRequirement: 'Team',
    ),
    Level(
      id: 30,
      name: 'Echoes of Earth',
      subtitle: 'Final Boss: Sequenced team power execution.',
      theme: 'Team',
      backgroundAsset: 'backgrounds/water_ocean.png',
      heroRequirement: 'Team',
    ),
  ];
}
